const data = [
    {
        id: 1, title: "Vinh Danh 295 sinh viên FPT Polytechnic học kỳ Spring 2018", desc1: "Tối ngày 16/06/2018, Cao đẳng FPT Polytechnic", desc2: "Hà Nội đã tổ chức Lễ tôn vinh Ong vàng Poly", desc3: "tuyên dương 295 cá nhân và tập thể có thành", desc4: "tích xuất sắc trong học tập cũng như hoạt...", img: "./img/img1.jpg",
    },
    {
        id: 2, title: "Sinh viên khối ngành Kinh tế học cách chạm vào cảm xúc", desc1: "Với sự tham gia của chuyên gia trong lĩnh vực", desc2: "kinh doanh, chương trình đã thu hút đông đảo", desc3: "sinh viên Cao đẳng FPT Polytechnic tham dự.", desc4: "Đặc biệt các bạn sinh viên bị lôi cuốn bởi...", img: "./img/img2.jpg",
    },
    {
        id: 3, title: "Sinh viên Fpoly trải nghiệm thực tế tại Mường Thanh Luxury", desc1: "Với triết lý đào tạo Thực học - Thực nghiệp ,", desc2: "Cao đẳng FPT Polytechnic Đà Nẵng thường", desc3: "xuyên tổ chức cho sinh viên tham quan các", desc4: "đơn vị doanh nghiệp...", img: "./img/img3.jpg",
    },
];
export default data;
const Products = [
    {
        createdAt: "2022-01-10T07:26:52.549Z",
        name: "Annie Stroman",
        img: "http://placeimg.com/640/480/fashion",
        desc: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
        id: "1",
    },
    {
        createdAt: "2022-01-10T20:33:27.477Z",
        name: "Yolanda Roob",
        img: "http://placeimg.com/640/480/sports",
        desc: "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
        id: "2",
    },
    {
        createdAt: "2022-01-11T03:36:13.571Z",
        name: "Rufus Konopelski",
        img: "http://placeimg.com/640/480/transport",
        desc: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
        id: "3",
    },
    {
        createdAt: "2022-01-10T04:45:32.422Z",
        name: "Ray Boyle",
        img: "http://placeimg.com/640/480/transport",
        desc: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
        id: "4",
    },
    {
        createdAt: "2022-01-10T10:56:22.073Z",
        name: "Jacqueline Hills",
        img: "http://placeimg.com/640/480/fashion",
        desc: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
        id: "5",
    },
    {
        createdAt: "2022-01-11T00:27:12.664Z",
        name: "Lee Abbott",
        img: "http://placeimg.com/640/480/people",
        desc: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
        id: "6",
    },
    {
        createdAt: "2022-01-10T14:41:53.412Z",
        name: "Muriel Okuneva",
        img: "http://placeimg.com/640/480/business",
        desc: "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
        id: "7",
    },
    {
        createdAt: "2022-01-10T16:35:33.134Z",
        name: "Tara Gutmann",
        img: "http://placeimg.com/640/480/business",
        desc: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        id: "8",
    },
    {
        createdAt: "2022-01-10T21:17:56.264Z",
        name: "Rudy Trantow",
        img: "http://placeimg.com/640/480/city",
        desc: "The Football Is Good For Training And Recreational Purposes",
        id: "9",
    },
    {
        createdAt: "2022-01-10T23:35:59.996Z",
        name: "Wayne Lang V",
        img: "http://placeimg.com/640/480/food",
        desc: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        id: "10",
    },
    {
        createdAt: "2022-01-10T14:22:10.945Z",
        name: "Esther Morar",
        img: "http://placeimg.com/640/480/nightlife",
        desc: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        id: "11",
    },
    {
        createdAt: "2022-01-10T11:38:45.275Z",
        name: "Sonya Prohaska Sr.",
        img: "http://placeimg.com/640/480/food",
        desc: "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
        id: "12",
    },
    {
        createdAt: "2022-01-10T14:45:44.448Z",
        name: "Levi Turcotte",
        img: "http://placeimg.com/640/480/city",
        desc: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
        id: "13",
    },
    {
        createdAt: "2022-01-10T06:52:23.902Z",
        name: "Eddie Crona",
        img: "http://placeimg.com/640/480/technics",
        desc: "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
        id: "14",
    },
    {
        createdAt: "2022-01-10T15:09:36.220Z",
        name: "Heather Labadie",
        img: "http://placeimg.com/640/480/sports",
        desc: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        id: "15",
    },
    {
        createdAt: "2022-01-11T03:02:51.996Z",
        name: "Daryl Hettinger I",
        img: "http://placeimg.com/640/480/nature",
        desc: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        id: "16",
    },
    {
        createdAt: "2022-01-10T20:16:49.772Z",
        name: "Heather Miller",
        img: "http://placeimg.com/640/480/nightlife",
        desc: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        id: "17",
    },
];
